### ISSUE TITLE
Clean up FIDOO code and commit code as library

### ISSUE THREAD

**Issue by techmaurice** [techmaurice/fidoo#4]
Clean up FIDOO code and commit code so it can be used as library. This also means the code will be open sourced for use in web apps.

**Comment by techmaurice** [comment]
The library in progress now runs in both browser and node.js.

**Comment by florianajir** [comment]
:+1:

**Comment by techmaurice** [comment]
@florianajir ;) Yeah!

Really need to get used to the asynchronicity of executions in node.js. Even the console.log is out of order sometimes ;)

**Comment by techmaurice** [comment]
Fidoo version 0.1.0 is stable and runs in browser and node.js, now also to be used as library
